common:
  seed: 42
  num_workers: 4
  gpu_devices: 1
  gpu: 0
  dist_url: tcp://127.0.0.1:32460
  dist_backend: nccl
  rank: 0
  world_size: 1
  distributed: false
  save_dir: ./cola
  n_epochs: 20
  
dataset:
  name: cola
  num_classes: 2
  batch_size: 16
  max_seq_length: 200
  pad_to_max_length: true

optimizer:
  name: adamw
  weight_decay: 0.1
  learning_rate: 2e-05
  adam_betas: [0.9, 0.98]
  adam_eps: 1e-06

lr_scheduler:
  name: linear_decay
  total_steps: 5000
  warmup_steps: 320
  warmup_ratio: 0.1

model:
  name: roberta-base
  hidden_size: 768
  dropout: 0.1
  attention_dropout: 0.1