common:
  seed: 42
  gpu_devices: 2
  gpu: 0,1
  dist_url: tcp://127.0.0.1:32466
  dist_backend: nccl
  rank: 0
  world_size: 1
  distributed: true
  save_dir: ./sst2
  n_epochs: 20

dataset:
  name: sst2
  num_classes: 2
  num_workers: 4
  batch_size: 32
  max_seq_length: 600
  pad_to_max_length: true
  save_dir: ./glue-v2
  
optimizer:
  name: adamw
  weight_decay: 0.1
  learning_rate: 1e-05
  adam_betas: [0.9, 0.98]
  adam_eps: 1e-06

lr_scheduler:
  name: linear_decay
  warmup_ratie: 0.1

model:
  name: roberta-base
  hidden_size: 768
  dropout: 0.1
  attention_dropout: 0.1